security:
  basic:
    enabled: true

management:
  security:
    enabled: true
    
logging:
  level:
    io:
      pivotal: DEBUG

greeting:
  displayFortune: true
  
quoteServiceURL: http://quote-service-qa.cfapps.io/quote
